version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports:
    - "5000:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=luis
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "luis@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "90:80"